name: Documentation
description: Improvements or fixes to docs
title: "[Docs]: "
labels: ["documentation"] 

body:
  - type: textarea
    id: issue
    attributes:
      label: What needs improvement?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change
